= Ideenreview

== Beschreibung der Idee
* *Problem:* 
** bisher werden Stimmen von Wahlen nur analog ausgewertet -> enormer Aufwand/ Fehleranfälligkeit und viele Freiwillige nötig
** Briefwahl/Wahllokale mit viel Material- und Kostenaufwand
* *Idee:*
** Online-Wahlplattform, die Nutzer verifiziert, einen Schritt-für-Schritt-Wahlprozess ermöglicht und die Stimmen digital auswertet
** *Ziel*: Wahlbeteiligung erhöhen, Kosten und Aufwand reduzieren, Fehler minimieren

== Aussehen der Idee in idealer Welt
* einfache, intuitive Benutzeroberfläche mit Barrierefreiheit und Mehrsprachigkeit
** Dashboard mit allen wichtigen Informationen (Wahltermin, Auswertung vergangener Wahlen, Informationsbutton mit Verlinkungen zu offiziellen Parteiprogrammen und Wahl-O-Mat etc.)
** Schritt-für-Schritt-Wahlprozess mit Erklärungen und Hilfestellungen
* einfacher Zugang als Web-App, auch für ältere Menschen
* schnell und sichere Online-Verifizierung (Kooperation mit PostID, BundID, etc.)
* Sicherheit, Vertraulichkeit und Datenschutz gewährleistet
* einfache Auswertung der Stimmen und schnelle Ergebnisse in Form von Diagrammen bereitgestellt

== Was soll App nicht sein?
* kein Ersatz für Wahllokale oder Briefwahl, sondern Ergänzung
* keine politisches Meinungs- und Diskussionsportal
* keine Informationsplattform für Parteien und Programme
* keine universelle Beteilungsplattform, sondern nur für Wahlen und offizielle Bürgerumfragen (keine Petitionen, etc.)

== Kernfunktionen
* Benutzerregistrierung und -verifizierung
* Dashboard mit: Wahltermin, Auswertung vergangener Wahlen, Informationsverlinkungen, etc.
* Schritt-für-Schritt-Wahlprozess mit Erklärungen und Hilfestellungen
** Bestätigungs- und Korrektuseite vor Absenden der Stimme
* Barrierefreiheit
** für ältere Menschen 
** Sehbehinderte (z.B. Sprachausgabe)

== Zusätzliche/ Optionale Funktionen
* automatische Wahlkreiserkennung
* Mehrsprachigkeit
* E-Mail- bzw. Push-Benachrichtigung bei neuen Wahlen
* Real-Time-Stimmenzähler, wie viele Leute schon gewählt haben
* Dark-Mode/ individuelle Designanpassungen
* Hilfsperson für Menschen, die aus irgendeinem Grund nicht wählen können, bei Registrierung/Verifizierung berücksichtigen

== Ähnliche Applikation
* Swiss Post E-Voting App (Online-Wahlplattform einiger Schweizer Kantone als Pilotprojekt für elektronische Wahlen)
* Pilotprojekt bei US-Wahl
* E-Voting-System in Estland